### ISSUE TITLE
Search Followers

### ISSUE THREAD

**Issue by rahul286** [ronakchauhan/twitterconnect#1]
Search followers is not searching all followers.

If there is any tweeter API limit, may be you can index all followers using background jobs.

**Comment by ronakchauhan** [comment]
Twitter API has LIMIT option and i set it to 10 so that we can display it on page and that page design will not affect.

**Comment by rahul286** [comment]
https://dev.twitter.com/rest/reference/get/followers/list
https://dev.twitter.com/overview/api/cursoring

With cursoring you can get all followers. You can use localstorage in browser or a database/cache on your server and then send "search" requests there.
